version: '3.8'

services:
  dhruv-postgres:
    image: "postgres:12"
    restart: always
    container_name: dhruv-postgres

    environment:
      - POSTGRES_DB=pratideen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    volumes:
      - ./dhruv-data:/var/lib/postgresql/data/
      - ./peoduct/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    ports:
      - 5432:5432
        
  dhruv-disovery:
    build: ./disocvery
    container_name: dhruv-disovery

    ports:
      - 8082:8082

  dhruv-gateway:
    build: ./gateway
    container_name: dhruv-gateway
    
    environment:
      - DISCOVERY_SERVER=dhruv-disovery
      - DISCOVERY_PORT=8082
    ports:
      - 8081:8081
    links:
      - dhruv-disovery

  dhruv-product:
    build: ./product
    container_name: dhruv-product

    environment:
      - DB_SERVER=dhruv-postgres
      - POSTGRES_DB=pratideen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DISCOVERY_SERVER=dhruv-disovery
      - DISCOVERY_PORT=8082
    ports:
      - 8084:8084
    links:
      - dhruv-postgres
      - dhruv-disovery

  dhruv-ui:
    build: ./ui
    container_name: dhruv-ui
    ports:
      - 80:80
    links:
      - dhruv-gateway

  dhruv-ui5-admin:
    build: ./ui5-admin
    container_name: dhruv-ui5-admin
    ports:
      - 9000:80
    links:
      - dhruv-gateway