version: '3.8'

services:
  dhruv-postgres:
    image: "postgres:12"

    environment:
      - POSTGRES_DB=pratideen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./dhruv-data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

    ports:
      - 5432:5432

  dhruv-product:
    image: ajinkyadhote/dhruv-product
    environment:
      - DB_SERVER=dhruv-postgres
      - POSTGRES_DB=pratideen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DISCOVERY_SERVER=dhruv-disovery
      - DISCOVERY_PORT=8082
    ports:
      - 8084:8084

  dhruv-mills:
    image: ajinkyadhote/dhruv-mills
    environment:
      - DB_SERVER=dhruv-postgres
      - POSTGRES_DB=pratideen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DISCOVERY_SERVER=dhruv-disovery
      - DISCOVERY_PORT=8082
    ports:
      - 8085:8085

  dhruv-ui:
    image: ajinkyadhote/dhruv-ui
    ports:
      - 80:80

  dhruv-ui5-admin:
    image: ajinkyadhote/dhruv-ui5-admin
    ports:
      - 9000:80
